### ISSUE TITLE
Develop procedure and export of Kibana config 

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/archive-analytics#16]
## Motivation
...so that I can generate the reports for Kibana on another system than the current system

## Acceptance Criteria
**Given** a Kibana sitting on top of the registry that has reports and configuration created
**When I perform** an installation and deployment of a new registry and Kibana
**Then I expect** to be able to easily drop in the config so that the reports are automatically generated out of the box and/or with a procedure to do so.

## Engineering Details

- [x] procedure for exporting config (in README.md)
- [x] procedure for importing config (in README.md)
- [ ] add config to repo under new `conf/kibana` directory.

**Comment by tloubrieu-jpl** [comment]
@TWilson2017 is able to export the dashboard configuration from kibana

**Comment by TWilson2017** [comment]
Procedure for exporting config 

![image](https://user-images.githubusercontent.com/25163556/117218733-b2889e00-add1-11eb-997f-aff75e713792.png)

**Comment by TWilson2017** [comment]
procedure for importing config

![image](https://user-images.githubusercontent.com/25163556/117218777-d0560300-add1-11eb-915e-63d302b918d9.png)
