### ISSUE TITLE
As a manager, I want to know the current total volume of PDS holdings

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/archive-analytics#2]
## Motivation
...so that I can complete the quarterly report per NASA HQ request

## Additional Details
> Please prove any additional details or information that could help provide some context for the user story.

## Acceptance Criteria
**Given** *<a condition>*
**When I perform** *<an action>*
**Then I expect** *<the result>*

**Comment by TWilson2017** [comment]
Completed - 
![image](https://user-images.githubusercontent.com/25163556/116161655-21734200-a6c2-11eb-868a-6b0aa13ff56d.png)
