### ISSUE TITLE
As a PDS Project Office, I want to know the current total volume of PDS holdings

### ISSUE THREAD

**Issue by TWilson2017** [NASA-PDS/archive-analytics#6]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can complete the quarterly report per NASA HQ request

## Additional Details
> Please prove any additional details or information that could help provide some context for the user story.

## Acceptance Criteria
**Given** *<a condition>*
**When I perform** *<an action>*
**Then I expect** *<the result>*

**Comment by jordanpadams** [comment]
duplicate of #2
