### ISSUE TITLE
As a PDS Project Office, I want to know the historical total volume of PDS holdings over time

### ISSUE THREAD

**Issue by TWilson2017** [NASA-PDS/archive-analytics#7]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can complete the quarterly report per NASA HQ request

## Additional Details
> Please prove any additional details or information that could help provide some context for the user story.

## Acceptance Criteria
**Given** *<a condition>*
**When I perform** *<an action>*
**Then I expect** *<the result>*

**Comment by jordanpadams** [comment]
<img width="1669" alt="Screen Shot 2021-06-03 at 2 27 40 PM" src="https://user-images.githubusercontent.com/33492486/120714336-ebbb3900-c477-11eb-931c-8dc905819449.png">
